name: e2e-test

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/e2e-test.yaml
      - pkg/**
      - cmd/**
      - e2e_test/**
      - go.*
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/e2e-test.yaml
      - pkg/**
      - cmd/**
      - e2e_test/**
      - go.*

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.3
          cache: true
      - run: go build ./cmd/kubectl-external_forward
      - run: make -C e2e_test cluster
      - run: make -C e2e_test
