name: homebrew

on:
  push:
    branches: [ master ]
    paths:
      - .github/workflows/homebrew.yaml
      - '*.rb'
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/homebrew.yaml
      - '*.rb'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - uses: actions/checkout@v2
      - run: brew install kubectl-socat.rb
      - run: brew test kubectl-socat
