name: mirror

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/mirror.yaml
  schedule:
    - cron: 1 0 * * *

jobs:
  image:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        image:
          - src: envoyproxy/envoy:v1.17-latest
            dst: ghcr.io/int128/kubectl-external-forward/mirror/envoy
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - run: docker pull ${{ matrix.image.src }}
      - run: docker tag ${{ matrix.image.src }} ${{ matrix.image.dst }}
      - run: docker push ${{ matrix.image.dst }}
