name: socat

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/socat.yaml
  schedule:
    - cron: 1 0 * * *

jobs:
  # mirror https://hub.docker.com/r/alpine/socat to GHCR
  mirror-docker-hub-alpine-socat:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DOCKER_BUILDKIT: 1
      DOCKER_REPOSITORY: ghcr.io/${{ github.repository }}/mirror/alpine/socat
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin
      - run: docker pull alpine/socat
      - run: docker tag alpine/socat "$DOCKER_REPOSITORY"
      - run: docker push "$DOCKER_REPOSITORY"
