name: socat

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/socat.yaml
  schedule:
    - cron: 1 0 * * *

jobs:
  # mirror https://hub.docker.com/r/alpine/socat to GHCR
  mirror-docker-hub-alpine-socat:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        image:
          - ghcr.io/int128/kubectl-external-forward/mirror/alpine/socat
          - ghcr.io/int128/kubectl-socat/mirror/alpine/socat
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - run: docker pull alpine/socat
      - run: docker tag alpine/socat ${{ matrix.image }}
      - run: docker push ${{ matrix.image }}
